### ISSUE TITLE
RunneSet PVs created by volumeClaimTemplates are not being reused

### ISSUE THREAD

**Issue by Diontsoumas** [actions-runner-controller/actions-runner-controller#1934]
### Checks

- [X] I've already read https://github.com/actions-runner-controller/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.26.0

### Helm Chart Version

0.21.0

### CertManager Version

1.8.1

### Deployment Method

Helm

### cert-manager installation

Cert manager has been installed from the official source

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions-runner-controller/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions-runner-controller/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: ga-runner-deployment-default
  namespace: system-actions-runner
spec:
  labels:
    - gw-hosted
    - default 
  selector:
    matchLabels:
      type: gw-hosted
      machine-type: default
  dockerdWithinRunnerContainer: true
  organization: #################
  serviceName: gw-hosted-default
  template:
    metadata:
      labels:
        type: gw-hosted
        machine-type: default
    spec:
      containers:
      - name: runner
        image: summerwind/actions-runner-dind:v2.298.2-ubuntu-20.04-e1762ba
        resources:
          limits:
            cpu: 3
            memory: 6Gi
          requests:
            cpu: 3
            memory: 6Gi
        volumeMounts:
        - name: var-lib-docker
          mountPath: /var/lib/docker 
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: github_actions
      - effect: NoSchedule
        key: type
        operator: Equal
        value: default
      nodeSelector:
        role: github-actions-runners
        type: default

  volumeClaimTemplates:
  - metadata:
      name: var-lib-docker
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 500Gi
      storageClassName: arc-var-lib-docker 

----------

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: arc-var-lib-docker
parameters:
  type: pd-standard
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
```

### To Reproduce

```markdown
Create a pool of RunnerSets with volumeClaimTemplates for docker caching (irrelevant), have them up and running for a while, then check how many PVs are in the cluster.
```

### Describe the bug

While I see in the logs that the controller for the PVCs is working correctly (PVCs are being properly deleted and their associate PVs are freed), those PVs are not always being re-used. In our case, we always have 16 pods waiting for jobs, and there are always 16 PVCs laying around. I would expect some more PVs, but from our Grafana dashboards it's clear that they keep getting spawned (given enough time).

![Screenshot 2022-10-18 at 11 42 12 PM](https://user-images.githubusercontent.com/5954957/196540913-a1198254-d4df-4ad0-9b8b-39945eb50087.png)

The green line are the PVCs, and the spikes I believe are because the nodepool uses preemptible nodes (so they often get deleted after 24h). I tried to replicate this in our testing cluster (which also has the same issue), but always the available PVs are been re-used -- it's only after a while that things go south.

<img width="976" alt="Screenshot 2022-10-18 at 11 49 33 PM" src="https://user-images.githubusercontent.com/5954957/196541923-0bc5ffe9-1447-4a3f-9a97-cea752667e8d.png">

This is our current PV status, after cleaning everything up 3 days ago. Currently there are 9 available PVs laying around and this number keeps increasing every day.
  

### Describe the expected behavior

The available PVs to actually be reused instead of new ones to be created.

### Whole Controller Logs

```shell
https://gist.github.com/Diontsoumas/f77030ec4d50b01510de364c87d0e41e
```

### Whole Runner Pod Logs

```shell
N/A
```

### Additional Context

I read about the ACT implementation in various threads and issues, and from what I understand ACT is only responsible for deleting the PVC / making the underlying PVs available. It's Kubernetes itself that actually re-uses PVs if they match the storage class of the PVC and are available, so I am not sure what is going on here -- we started adding alerts on those disks however, as it wasn't funny having 100s of them just sitting around without being used :)

**Comment by Diontsoumas** [comment]
![Screenshot 2022-10-19 at 12 44 44 PM](https://user-images.githubusercontent.com/5954957/196657197-7e9b07b8-82c5-4066-93bc-f807bcca8eab.png)

Digging some more into this, it seems that loads of pods get created on certain spikes, even though autoscaler is fixed (min=max). I think that preemptible nodes are to blame, will try to dig the controller logs during those spikes to get an idea about what is going on.

**Comment by Diontsoumas** [comment]
Updating the nodepool not to use preemptibles solves the issue. It's interesting that this happens, and obviously it's not ARC's issue, but this leaves the usage of preemptibles of the picture.

**Comment by serhij-matvejev** [comment]
Well, the issue is still relevant in case of using storageclass with `pd.csi.storage.gke.io` provisioner. The problem sometimes happens when the GKE worker just started. That is why in case of preemtibles the problem happens much more often. If you are not using preemptibles, but you are using HorizontalRunnerAutoscaler with GKE node autoscaler, then you will see growing amount of PVs.

If you use preemtibles and the node goes down and create a new one or/and
if you use HorizontalRunnerAutoscaler and GKE node autoscaler (scale up), then sometimes part of your runner PODs will be in Pending state.

**The bug:**
What is happening when the GKE worker just started? Then node turned `NotReady` to `Ready` status. Then Kubernetes scheduler assign/schedule some PODs to the node. Since your Pending runners are ready to be assigned to the worker, the PV is trying to be provisioned. But often the provisioner (based on the storageclass is csi driver) is still starting on this new worker. This is just a daemonset (`pdcsi-node` in kube-system). And if the provisioner (pdcsi-node POD) on this worker is not manage to start quite fast, then you will see such message in K8s events (in runner's namespace):
```
3m57s       Normal    WaitForPodScheduled      persistentvolumeclaim/var-lib-docker-ga-runner-deployment-mem-optimised-s6vgb-0   waiting for pod ga-runner-deployment-mem-optimised-s6vgb-0 to be scheduled

3m50s       Warning   ProvisioningFailed       persistentvolumeclaim/var-lib-docker-ga-runner-deployment-mem-optimised-s6vgb-0   failed to provision volume with StorageClass "arc-var-lib-docker": error generating accessibility requirements: no topology key found on CSINode gke-mycluster-github-actions-runners--1ce61e13-gdxd

3m42s       Normal    ExternalProvisioning     persistentvolumeclaim/var-lib-docker-ga-runner-deployment-mem-optimised-s6vgb-0   waiting for a volume to be created, either by external provisioner "pd.csi.storage.gke.io" or manually created by system administrator

3m42s       Normal    Provisioning             persistentvolumeclaim/var-lib-docker-ga-runner-deployment-mem-optimised-s6vgb-0   External provisioner is provisioning volume for claim "system-actions-runner/var-lib-docker-ga-runner-deployment-mem-optimised-s6vgb-0"

3m38s       Normal    ProvisioningSucceeded    persistentvolumeclaim/var-lib-docker-ga-runner-deployment-mem-optimised-s6vgb-0   Successfully provisioned volume pvc-df38a14a-9194-4467-b363-22dcf8f9f8ae
```
And instead of reusing some existing PV, it looks like it is always creating a new one.
I am not sure if it is something that could be fixed in ARC.

**Fast fix:**
Change the provisioner from csi (`pd.csi.storage.gke.io`) to In-Tree storage plugin (`kubernetes.io/gce-pd`) in your storageclass. It is enough to recreate the storageclass object. Example of the storageclass:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: arc-var-lib-docker
parameters:
  type: pd-standard
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
```

This is not the best fix, because CSI has to replace in-tree storage plugins. But it will work until GCP supports the storage plugin. It has to work with preemtibles and it will work with HorizontalRunnerAutoscaler + GKE node autoscaler. Just because the In-Tree provisioner will be "Ready" together with the GKE worker. Tested with HRA + node autoscaler on GKE v1.21.14 and v1.23.12.

I have noticed another problem which could create 1 or 2 extra PVs. It happens when you are using HorizontalRunnerAutoscaler and it scales down from `max` to `1` or `2` desired replicas. Your runner PODs are in Terminating state and it requires some seconds to switch PVs from Bound to Available - it is OK. But unfortunately sometimes it is terminating **all** runner PODs (not `max` `-` `desired`). So all old replicas are in Terminating and 1 or 2 new replicas scheduled and in ContainerCreating. All old PVs could not be detached yet, but new PODs demanded and obtained new PVs.

However it is not that tragic as previous issue with the csi. You will have one or two extra PVs. If all in Terminating repeats again and one or two PODs are going to be started, then it will just reuse these one or two extra PVs.

It looks like a bug in the action runner controller which should not terminate all pods if HRA desired is not `0`.
