### ISSUE TITLE
question, appling a downscale to  runnerdeployment not concentrate runners on the first node, so nodepool autoscaling can't downscale.

### ISSUE THREAD

**Issue by matteo-savore-deltatre** [actions-runner-controller/actions-runner-controller#299]
Hi , thank you for your work, love it.
I'm doing some experiments on my AKS with autoscale nodepool.

if a start applying a runner deployment with replica 1 to a nodepool autoscale (1  VM ) it puts the pod on this VM (obviously)
then I re-apply with replica 10 and correclty the nopool autoscale to 2 vms and all the runners are correctly started and spreaded acroos the nodes.
At this point i apply back replica 1.

should i get the pod on the first node ?
Actually i get the Pod on the second node and the nodepool is not able to downscale itself to 1 Vms as it was at the very beginning.
Is this an expected results? or i need to add something to get pods move to the very first node if there is room on it ?

Thank you

**Comment by mumoshu** [comment]
@matteo-savore-deltatre Hey! This is actually a good question. I believe that's due to that CA's default behavior is to [avoid evicting pods that are not backed by K8s deployment, replicaset, statefulset, or job](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node). Our runner pods are backed by Runner, RunnerReplicaSet, RunnerDeployment.

According to their doc, adding `"cluster-autoscaler.kubernetes.io/safe-to-evict": "true"` to your runner pods would force the CA to consider it for eviction.

Would you mind giving it a shot?

For your reference, I thought I've implemented the controller to inherit runner annotations to the runner pod. So, you should be able to add arbitrary runner pod annotations via `RunnerDeployment.Spec.Template.Metadata.Annotations` or `Runner.Metadata.Annotations` like e.g.:

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: example
spec:
  template:
    metadata:
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
    spec:
      repository: your/repo
```

**Comment by matteo-savore-deltatre** [comment]
unfortunately i still getting having pods on different nodes afted a downscale even if there are free resources on the first node:
`.....
 Namespace                   Name                                               CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                   ----                                               ------------  ----------  ---------------  -------------  ---
  actions-runner-system       linux-runner-knxz2-f2pm9                           100m (5%)     0 (0%)      512Mi (9%)       0 (0%)         5m31s
  actions-runner-system       linux-runner-knxz2-hf7g9                           100m (5%)     0 (0%)      512Mi (9%)       0 (0%)         3m59s
  actions-runner-system       linux-runner-knxz2-lc82p                           100m (5%)     0 (0%)      512Mi (9%)       0 (0%)         3m59s
  actions-runner-system       linux-runner-knxz2-wvzld                           100m (5%)     0 (0%)      512Mi (9%)       0 (0%)         3m58s
  actions-runner-system       test-actions-runner-controller-6696bd8d98-snxvx    0 (0%)        0 (0%)      0 (0%)           0 (0%)         16m
  cert-manager                cert-manager-58c8844bb8-tclq4                      0 (0%)        0 (0%)      0 (0%)           0 (0%)         3h57m
  cert-manager                cert-manager-cainjector-745768f6ff-w9fmk           0 (0%)        0 (0%)      0 (0%)           0 (0%)         3h57m
  cert-manager                cert-manager-webhook-67cc76975b-wzx9z              0 (0%)        0 (0%)      0 (0%)           0 (0%)         3h57m
  kube-system                 coredns-748cdb7bf4-86hvb                           100m (5%)     0 (0%)      70Mi (1%)        170Mi (3%)     4h1m
  kube-system                 coredns-748cdb7bf4-9d4l4                           100m (5%)     0 (0%)      70Mi (1%)        170Mi (3%)     4h
  kube-system                 coredns-autoscaler-868b684fd4-8ld7d                20m (1%)      0 (0%)      10Mi (0%)        0 (0%)         4h1m
  kube-system                 kube-proxy-g9krt                                   100m (5%)     0 (0%)      0 (0%)           0 (0%)         4h
  kube-system                 metrics-server-58fdc875d5-lbp72                    44m (2%)      0 (0%)      55Mi (1%)        0 (0%)         4h1m
  kube-system                 omsagent-cbzf4                                     75m (3%)      500m (26%)  225Mi (4%)       600Mi (11%)    4h
  kube-system                 omsagent-rs-5c9fff6594-5pgsf                       150m (7%)     1 (52%)     250Mi (4%)       1Gi (19%)      4h1m
  kube-system                 tunnelfront-67fd74fd4f-t5ltj                       10m (0%)      0 (0%)      64Mi (1%)        0 (0%)         4h1m
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                       Requests      Limits
  --------                       --------      ------
  cpu                            999m (52%)    1500m (78%)
  memory                         2792Mi (52%)  1964Mi (36%)
  ephemeral-storage              0 (0%)        0 (0%)
  hugepages-1Gi                  0 (0%)        0 (0%)
  hugepages-2Mi                  0 (0%)        0 (0%)
  attachable-volumes-azure-disk  0             0
Events:                          <none>
.........
  Namespace                   Name                        CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                   ----                        ------------  ----------  ---------------  -------------  ---
  actions-runner-system       linux-runner-knxz2-2jb7m    100m (5%)     0 (0%)      512Mi (9%)       0 (0%)         3m53s
  kube-system                 kube-proxy-ds4nf            100m (5%)     0 (0%)      0 (0%)           0 (0%)         2m31s
  kube-system                 omsagent-kc9x7              75m (3%)      500m (26%)  225Mi (4%)       600Mi (11%)    2m31s
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                       Requests     Limits
  --------                       --------     ------
  cpu                            275m (14%)   500m (26%)
  memory                         737Mi (13%)  600Mi (11%)
  ephemeral-storage              0 (0%)       0 (0%)
  hugepages-1Gi                  0 (0%)       0 (0%)
  hugepages-2Mi                  0 (0%)       0 (0%)
  attachable-volumes-azure-disk  0            0
`

any other suggestion ?

thank you

**Comment by mumoshu** [comment]
@matteo-savore-deltatre What's in logs from Cluster Autoscaler?

Also, are you sure there's any other pods on your second node that prevents it from deleting it?

CA's ["What types of pods can prevent CA from removing a node?"](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node) the most authoritative documentation that I can recommend for investigation.
